async function main() {
	const [owner, user, hacker] = await ethers.getSigners();
	const invalid               = "0x0000000000000000000000000000000000000000";
	const amount                = ethers.parseEther("0.00001");
    let contract                = null;

    contract = await ethers.deployContract("Instance", ["ethernaut0"]);
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Fallback");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Fallout");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("CoinFlip");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("CoinFlipExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Telephone");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("TelephoneExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Token", [amount], { from: owner });
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Delegate", [owner]);
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Force");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("ForceExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Vault", [ethers.encodeBytes32String("ethernaut8")]);
    await contract.waitForDeployment();
    contract = await ethers.deployContract("King", { from: owner, value: amount });
    await contract.waitForDeployment();
    contract = await ethers.deployContract("KingExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Reentrance");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("ReentranceExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Elevator");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("ElevatorExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Privacy", [[ethers.encodeBytes32String("ether"), ethers.encodeBytes32String("naut"), ethers.encodeBytes32String("12")]]);
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Gatekeeper");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("GatekeeperExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("GatekeeperTwo");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("GatekeeperTwoExploit", [contract], { from: hacker });
    await contract.waitForDeployment();
    contract = await ethers.deployContract("NaughtCoin", [owner]);
    await contract.waitForDeployment();
    contract = await ethers.deployContract("LibraryContract");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Preservation", [contract, contract]);
    await contract.waitForDeployment();
    contract = await ethers.deployContract("PreservationExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Recovery");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("RecoveryExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("MagicNumber");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("MagicNumberExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("AlienCodex");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("AlienCodexExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Denial");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("DenialExploit");
    await contract.waitForDeployment();
    contract = await ethers.deployContract("Shop");
    await contract.waitForDeployment();
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
