async function main() {
    const [owner, hacker]    = await ethers.getSigners();
    const amount             = ethers.parseEther("0.00001");
    let contract1, contract2 = null;

    contract1 = await ethers.deployContract("Instance", ["ethernaut0"]);
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Fallback");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Fallout");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("CoinFlip");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("CoinFlipExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Telephone");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("TelephoneExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Token", [amount], { from: owner });
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Delegate", [owner]);
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Force");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("ForceExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Vault", [ethers.encodeBytes32String("ethernaut8")]);
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("King", { from: owner, value: amount });
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("KingExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Reentrance");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("ReentranceExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Elevator");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("ElevatorExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Privacy", [[ethers.encodeBytes32String("ether"), ethers.encodeBytes32String("naut"), ethers.encodeBytes32String("12")]]);
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Gatekeeper");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("GatekeeperExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("GatekeeperTwo");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("GatekeeperTwoExploit", [contract1], { signer: hacker });
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("NaughtCoin", [owner]);
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("LibraryContract");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Preservation", [contract1, contract1]);
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("PreservationExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Recovery");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("RecoveryExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("MagicNumber");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("MagicNumberExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("AlienCodex");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("AlienCodexExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Denial");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("DenialExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Shop");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("ShopExploit");
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("Dex", { from: owner });
    await contract1.waitForDeployment();
    contract2 = await ethers.deployContract("SwappableToken", [contract1, "Token 1", "T1", 100], { signer: owner });
    await contract2.waitForDeployment();
    contract2 = await ethers.deployContract("SwappableToken", [contract1, "Token 2", "T2", 100], { signer: owner });
    await contract2.waitForDeployment();
    contract1 = await ethers.deployContract("DexTwo", { from: owner });
    await contract1.waitForDeployment();
    contract2 = await ethers.deployContract("SwappableToken", [contract1, "Token 1", "T1", 100], { signer: owner });
    await contract2.waitForDeployment();
    contract2 = await ethers.deployContract("SwappableToken", [contract1, "Token 2", "T2", 100], { signer: owner });
    await contract2.waitForDeployment();
    contract1 = await ethers.deployContract("DexTwoExploit", ["Exploit 1", "E1", 200], { signer: hacker });
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("DexTwoExploit", ["Exploit 2", "E1", 200], { signer: hacker });
    await contract1.waitForDeployment();
    contract1 = await ethers.deployContract("PuzzleWallet");
    await contract1.waitForDeployment();
    contract2 = await ethers.deployContract("PuzzleProxy", [owner, contract1, contract1.interface.encodeFunctionData("init", [amount * BigInt(1000)])]);
    await contract2.waitForDeployment();
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
