const Instance             = artifacts.require("Instance");
const Fallback             = artifacts.require("Fallback");
const Fallout              = artifacts.require("Fallout");
const CoinFlip             = artifacts.require("CoinFlip");
const CoinFlipExploit      = artifacts.require("CoinFlipExploit");
const Telephone            = artifacts.require("Telephone");
const TelephoneExploit     = artifacts.require("TelephoneExploit");
const Token                = artifacts.require("Token");
const Delegate             = artifacts.require("Delegate");
const Force                = artifacts.require("Force");
const ForceExploit         = artifacts.require("ForceExploit");
const Vault                = artifacts.require("Vault");
const King                 = artifacts.require("King");
const KingExploit          = artifacts.require("KingExploit");
const Reentrance           = artifacts.require("Reentrance");
const ReentranceExploit    = artifacts.require("ReentranceExploit");
const Elevator             = artifacts.require("Elevator");
const ElevatorExploit      = artifacts.require("ElevatorExploit");
const Privacy              = artifacts.require("Privacy");
const Gatekeeper           = artifacts.require("Gatekeeper");
const GatekeeperExploit    = artifacts.require("GatekeeperExploit");
const GatekeeperTwo        = artifacts.require("GatekeeperTwo");
const GatekeeperTwoExploit = artifacts.require("GatekeeperTwoExploit");
const NaughtCoin           = artifacts.require("NaughtCoin");
const LibraryContract      = artifacts.require("LibraryContract");
const Preservation         = artifacts.require("Preservation");
const PreservationExploit  = artifacts.require("PreservationExploit");
const Recovery             = artifacts.require("Recovery");
const RecoveryExploit      = artifacts.require("RecoveryExploit");
const MagicNumber          = artifacts.require("MagicNumber");
const MagicNumberExploit   = artifacts.require("MagicNumberExploit");
const AlienCodex           = artifacts.require("AlienCodex");
const AlienCodexExploit    = artifacts.require("AlienCodexExploit");
const Denial               = artifacts.require("Denial");
const DenialExploit        = artifacts.require("DenialExploit");

module.exports = function (deployer, network, accounts) {
	const owner  = accounts[0];
	const hacker = accounts[2];
	const amount = web3.utils.toWei("0.00001", "ether");

	deployer.deploy(Instance, "ethernaut0");
	deployer.deploy(Fallback);
	deployer.deploy(Fallout);
	deployer.deploy(CoinFlip);
	deployer.deploy(CoinFlipExploit);
	deployer.deploy(Telephone);
	deployer.deploy(TelephoneExploit);
	deployer.deploy(Token, amount, { from: owner });
	deployer.deploy(Delegate, owner);
	deployer.deploy(Force);
	deployer.deploy(ForceExploit);
	deployer.deploy(Vault, web3.utils.utf8ToHex("ethernaut8"));
	deployer.deploy(King, { from: owner, value: amount });
	deployer.deploy(KingExploit);
	deployer.deploy(Reentrance);
	deployer.deploy(ReentranceExploit);
	deployer.deploy(Elevator);
	deployer.deploy(ElevatorExploit);
	deployer.deploy(Privacy, [web3.utils.padRight(web3.utils.asciiToHex("ether"), 64), web3.utils.padRight(web3.utils.asciiToHex("naut"), 64), web3.utils.padRight(web3.utils.asciiToHex("12"), 64)]);
	deployer.deploy(Gatekeeper);
	deployer.deploy(GatekeeperExploit);
	deployer.deploy(GatekeeperTwo).then(function() { return deployer.deploy(GatekeeperTwoExploit, GatekeeperTwo.address, { from: hacker }); });
	deployer.deploy(NaughtCoin, owner);
	deployer.deploy(LibraryContract).then(function() { return deployer.deploy(Preservation, LibraryContract.address, LibraryContract.address); });
	deployer.deploy(PreservationExploit);
	deployer.deploy(Recovery);
	deployer.deploy(RecoveryExploit);
	deployer.deploy(MagicNumber);
	deployer.deploy(MagicNumberExploit);
	deployer.deploy(AlienCodex);
	deployer.deploy(AlienCodexExploit);
	deployer.deploy(Denial);
	deployer.deploy(DenialExploit);
};
